version: "3.8"
networks:
    default:
        name: data-extractor-network
        external: true
services:
    data-extractor:
        image: data-extractor
        container_name: data-extractor
        volumes:
            - ${SECRETS_DIR}:/secrets
            - ../extracts:/app
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS_data} 
            GCP_PROJECT: ${GCP_PROJECT}
            GCP_ZONE: ${GCP_ZONE}
            GCP_BUCKET: ${GCP_BUCKET}
            GCP_BUCKET_BRONZE_FOLDER: ${GCP_BUCKET_BRONZE_FOLDER}
